In [71]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

In [74]:
df = pd.read_csv("Salary_Data.csv")

In [76]:
df.head(5)

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [78]:
df.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

In [80]:
df.dropna(inplace = True) #Exact match

In [82]:
df.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

In [84]:
df.shape

(30, 2)

In [86]:
x = df[['YearsExperience']]
y = df['Salary']

In [88]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train, y_test = train_test_split(x , y , test_size = 0.2  , random_state = 42)

In [89]:
from sklearn.linear_model import LinearRegression

In [90]:
lr = LinearRegression()

In [92]:
lr.fit(X_train , y_train)

LinearRegression()

In [93]:
y_pred = lr.predict(X_test)

In [98]:
y_pred

array([115790.21011287,  71498.27809463, 102596.86866063,  75267.80422384,
        55477.79204548,  60189.69970699])

In [100]:
X_test

    YearsExperience
27              9.6
15              4.9
23              8.2
17              5.3
8               3.2
9               3.7

In [102]:
y_test

27    112635.0
15     67938.0
23    113812.0
17     83088.0
8      64445.0
9      57189.0
Name: Salary, dtype: float64

In [104]:
from sklearn.metrics import r2_score

In [106]:
r2 = r2_score(y_test ,y_pred)

In [108]:
r2

0.9024461774180497

In [110]:
m = lr.coef_
m

array([9423.81532303])

In [112]:
c = lr.intercept_
c

25321.583011776813

In [ ]:
m *4.0  + c

In [ ]:
m=model.pickle("Linear_Regression_Batch_1")

In [ ]:
sns.scatterplot(x = 'Years of Experience', 'age' , y = 'Salary' , data = df)
plt.plot(X_test , lr.predict(X_test) , color = 'red')

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
print('MSE: ', mean_squared_error(y_test , y_pred))

In [ ]:
age=int(input("enter a no."))
if age<18:
        print("you can not vote")
else:
       print("vote")

In [ ]:
for i in range(0,12,2):
    print(i)

In [ ]:
for i in range(1,11):
    print(2*i)

In [7]:
for i in range(1,11):
    print(f"2 x {i} =",2*i)

2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20

In [22]:
a=10
if a<10:
    print("hi")
elif a>10:
    print("meow")
else:
    print("mansi")

mansi

In [24]:
a=[1,2,"a","w",2.3]
print(a)

[1, 2, 'a', 'w', 2.3]

In [26]:
a.append(2)
print(a)

[1, 2, 'a', 'w', 2.3, 2]

In [28]:
a.pop()

2

In [30]:
a

[1, 2, 'a', 'w', 2.3]

In [32]:
a.remove('a')

In [34]:
a

[1, 2, 'w', 2.3]

In [36]:
r2 score jitna kam hoga utna model accha hoga , mse jitna jyada hoga model utnA KHRAB HOGA

SyntaxError: invalid syntax (2776899313.py, line 1)

In [38]:
import streamlit as st
import pickle
import numpy as np

model = pickle.load(open("model.pkl","rb"))

st.title("House Price Prediction")

area = st.number_input("Area")
bedrooms = st.number_input("Bedrooms")
age = st.number_input("Age")

if st.button("Predict"):
    result = model.predict([[area,bedrooms,age]])
    st.success(f"Price: {result[0]}")

FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'

In [ ]:
import streamlit as st

In [ ]:
st.title("house prediction model")

In [19]:
streamlit run Linear_Regression_Batch_1

SyntaxError: invalid syntax (1694527579.py, line 1)

###

In [ ]:
missing values , rename, duplicates, outliers

In [ ]:
y = mx + c

# Machine learning model steps

In [ ]:
1.import all libraries (numpy , pandas , matplotlib,sckit-learn ,tensorflow , keras.)

In [ ]:
2.Data import using pandas (pd.read_csv , pd.read_excel)

In [ ]:
3. EDA or preprocessing (Data cleaning , encoding , transforming , scaling )

In [ ]:
4. you need to make target variables x,y :,DATA divide into two parts : Training , Testing (train_test_split, 80,20)

In [ ]:
5. model import (lr=linearregression())

In [ ]:
6. Training data fitted into model .(lr.fit())

In [ ]:
7. Make predictions(lr.predict)

In [ ]:
8. check the evaluation matrices(r2score,accuracy score,f1score )

In [ ]:
9.convert model into pkl file .

In [ ]:
10. making the gui.

In [ ]:
11. pkl file adjust into gui code.