In [4]:
import pandas as pd
import pickle
import sklearn
import warnings
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsRegressor

In [5]:
df=pd.read_csv("Food_Delivery_Times.csv")

In [6]:
df

,Order_ID,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,522,7.93,Windy,Low,Afternoon,Scooter,12,1.0,43
1,738,16.42,Clear,Medium,Evening,Bike,20,2.0,84
2,741,9.52,Foggy,Low,Night,Scooter,28,1.0,59
3,661,7.44,Rainy,Medium,Afternoon,Scooter,5,1.0,37
4,412,19.03,Clear,Low,Morning,Bike,16,5.0,68
...,...,...,...,...,...,...,...,...,...
995,107,8.50,Clear,High,Evening,Car,13,3.0,54
996,271,16.28,Rainy,Low,Morning,Scooter,8,9.0,71
997,861,15.62,Snowy,High,Evening,Scooter,26,2.0,81
998,436,14.17,Clear,Low,Afternoon,Bike,8,0.0,55
999,103,6.63,Foggy,Low,Night,Scooter,24,3.0,58

In [7]:
df.head()

,Order_ID,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,522,7.93,Windy,Low,Afternoon,Scooter,12,1.0,43
1,738,16.42,Clear,Medium,Evening,Bike,20,2.0,84
2,741,9.52,Foggy,Low,Night,Scooter,28,1.0,59
3,661,7.44,Rainy,Medium,Afternoon,Scooter,5,1.0,37
4,412,19.03,Clear,Low,Morning,Bike,16,5.0,68

In [8]:
df.tail()

,Order_ID,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
995,107,8.50,Clear,High,Evening,Car,13,3.0,54
996,271,16.28,Rainy,Low,Morning,Scooter,8,9.0,71
997,861,15.62,Snowy,High,Evening,Scooter,26,2.0,81
998,436,14.17,Clear,Low,Afternoon,Bike,8,0.0,55
999,103,6.63,Foggy,Low,Night,Scooter,24,3.0,58

In [9]:
df.describe()

,Order_ID,Distance_km,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
count,1000.000000,1000.000000,1000.000000,970.000000,1000.000000
mean,500.500000,10.059970,16.982000,4.579381,56.732000
std,288.819436,5.696656,7.204553,2.914394,22.070915
min,1.000000,0.590000,5.000000,0.000000,8.000000
25%,250.750000,5.105000,11.000000,2.000000,41.000000
50%,500.500000,10.190000,17.000000,5.000000,55.500000
75%,750.250000,15.017500,23.000000,7.000000,71.000000
max,1000.000000,19.990000,29.000000,9.000000,153.000000

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Order_ID                1000 non-null   int64
 1   Distance_km             1000 non-null   float64
 2   Weather                 970 non-null    object
 3   Traffic_Level           970 non-null    object
 4   Time_of_Day             970 non-null    object
 5   Vehicle_Type            1000 non-null   object
 6   Preparation_Time_min    1000 non-null   int64
 7   Courier_Experience_yrs  970 non-null    float64
 8   Delivery_Time_min       1000 non-null   int64
dtypes: float64(2), int64(3), object(4)
memory usage: 70.4+ KB

In [11]:
df.isnull().sum()

Order_ID                   0
Distance_km                0
Weather                   30
Traffic_Level             30
Time_of_Day               30
Vehicle_Type               0
Preparation_Time_min       0
Courier_Experience_yrs    30
Delivery_Time_min          0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.dropna(inplace = True)

In [14]:
df.isnull().sum()

Order_ID                  0
Distance_km               0
Weather                   0
Traffic_Level             0
Time_of_Day               0
Vehicle_Type              0
Preparation_Time_min      0
Courier_Experience_yrs    0
Delivery_Time_min         0
dtype: int64

In [22]:
df.shape

(883, 9)

In [23]:
df["Weather"].unique()

array(['Windy', 'Clear', 'Foggy', 'Rainy', 'Snowy'], dtype=object)

In [24]:
df["Traffic_Level"].unique()

array(['Low', 'Medium', 'High'], dtype=object)

In [25]:
df["Time_of_Day"].unique()

array(['Afternoon', 'Evening', 'Night', 'Morning'], dtype=object)

In [26]:
df["Vehicle_Type"].unique()

array(['Scooter', 'Bike', 'Car'], dtype=object)

In [27]:
df['Weather']=df['Weather'].map ({"Windy":0, "Clear":1, "Foggy":2, "Rainy":3, "Snowy":4})
df['Traffic_Level']=df['Traffic_Level'].map ({"Low":0, "Medium":1, "High":2})
df['Time_of_Day']=df['Time_of_Day'].map ({"Afternoon":0, "Evening":1, "Night":2, "Morning":3})
df['Vehicle_Type']=df['Vehicle_Type'].map ({"Scooter":0, "Bike":1, "Car":2})

In [28]:
df

,Order_ID,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,522,7.93,0,0,0,0,12,1.0,43
1,738,16.42,1,1,1,1,20,2.0,84
2,741,9.52,2,0,2,0,28,1.0,59
3,661,7.44,3,1,0,0,5,1.0,37
4,412,19.03,1,0,3,1,16,5.0,68
...,...,...,...,...,...,...,...,...,...
995,107,8.50,1,2,1,2,13,3.0,54
996,271,16.28,3,0,3,0,8,9.0,71
997,861,15.62,4,2,1,0,26,2.0,81
998,436,14.17,1,0,0,1,8,0.0,55
999,103,6.63,2,0,2,0,24,3.0,58

In [49]:
max_value = df['Distance_km'].max()

print(f"The maximum value is: {max_value}")

The maximum value is: 19.99

In [29]:
x= df.drop(columns=["Order_ID", "Delivery_Time_min"])
y = df["Delivery_Time_min"]

In [40]:
X_train, X_test, y_train, y_test= train_test_split (x, y, test_size=0.2, random_state=42)

In [41]:
knr= KNeighborsRegressor(n_neighbors=6)

In [42]:
knr.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=6)

In [43]:
y_pred=knr.predict(X_test)

In [44]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("MAE :", mean_absolute_error(y_test, y_pred))
print("MSE :", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R² Score:", r2_score(y_test, y_pred))

MAE : 7.209981167608286
MSE : 101.14830508474576
RMSE: 10.057251368278799
R² Score: 0.7525243084738419

In [45]:
with open("KNN_Regressor_pickle.pkl", "wb") as file:
    pickle.dump( knr, file)