In [51]:
import pandas as pd
import warnings
import sklearn
from sklearn.model_selection import train_test_split
import pickle
import seaborn as sns

In [52]:
df= pd.read_csv("Data for repository.csv")

In [53]:
df

,Movie_Name,Release_Period,Whether_Remake,Whether_Franchise,Genre,New_Actor,New_Director,New_Music_Director,Lead_Star,Director,Music_Director,Number_of_Screens,Revenue(INR),Budget(INR)
0,Golden Boys,Normal,No,No,suspense,Yes,No,No,Jeet Goswami,Ravi Varma,Baba Jagirdar,5,5000000,85000
1,Kaccha Limboo,Holiday,No,No,drama,Yes,No,Yes,Karan Bhanushali,Sagar Ballary,Amardeep Nijjer,75,15000000,825000
2,Not A Love Story,Holiday,No,No,thriller,No,No,No,Mahie Gill,Ram Gopal Verma,Sandeep Chowta,525,75000000,56700000
3,Qaidi Band,Holiday,No,No,drama,Yes,No,No,Aadar Jain,Habib Faisal,Amit Trivedi,800,210000000,4500000
4,Chaatwali,Holiday,No,No,adult,Yes,Yes,Yes,Aadil Khan,Aadil Khan,Babloo Ustad,1,1000000,1075000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1693,Fight Club,Holiday,No,No,action,No,Yes,No,Zayed Khan,Vikram Chopra,Pritam,375,82500000,88862500
1694,Strings Of Paasion,Normal,No,No,drama,No,Yes,Yes,Zeenat Aman,Sanghamitra Chaudhuri,Dev Sikdar,10,8000000,70000
1695,Dunno Y Na Jaane Kyun,Normal,No,No,drama,No,No,No,Zeenat Aman,Sanjay Sharma,Nikhil,20,12500000,850000
1696,Taj Mahal - An Eternal Love Story,Normal,No,No,drama,No,Yes,No,Zulfi Sayed,Akbar Khan,Naushad,135,100000000,31065000
1697,Mr. Hot Mr. Kool,Normal,No,No,comedy,No,No,Yes,Zulfi Sayed,Partho Ghosh,Rishi - Ranjit,30,27500000,1300000

In [54]:
df.head()

,Movie_Name,Release_Period,Whether_Remake,Whether_Franchise,Genre,New_Actor,New_Director,New_Music_Director,Lead_Star,Director,Music_Director,Number_of_Screens,Revenue(INR),Budget(INR)
0,Golden Boys,Normal,No,No,suspense,Yes,No,No,Jeet Goswami,Ravi Varma,Baba Jagirdar,5,5000000,85000
1,Kaccha Limboo,Holiday,No,No,drama,Yes,No,Yes,Karan Bhanushali,Sagar Ballary,Amardeep Nijjer,75,15000000,825000
2,Not A Love Story,Holiday,No,No,thriller,No,No,No,Mahie Gill,Ram Gopal Verma,Sandeep Chowta,525,75000000,56700000
3,Qaidi Band,Holiday,No,No,drama,Yes,No,No,Aadar Jain,Habib Faisal,Amit Trivedi,800,210000000,4500000
4,Chaatwali,Holiday,No,No,adult,Yes,Yes,Yes,Aadil Khan,Aadil Khan,Babloo Ustad,1,1000000,1075000

In [55]:
df.tail()

,Movie_Name,Release_Period,Whether_Remake,Whether_Franchise,Genre,New_Actor,New_Director,New_Music_Director,Lead_Star,Director,Music_Director,Number_of_Screens,Revenue(INR),Budget(INR)
1693,Fight Club,Holiday,No,No,action,No,Yes,No,Zayed Khan,Vikram Chopra,Pritam,375,82500000,88862500
1694,Strings Of Paasion,Normal,No,No,drama,No,Yes,Yes,Zeenat Aman,Sanghamitra Chaudhuri,Dev Sikdar,10,8000000,70000
1695,Dunno Y Na Jaane Kyun,Normal,No,No,drama,No,No,No,Zeenat Aman,Sanjay Sharma,Nikhil,20,12500000,850000
1696,Taj Mahal - An Eternal Love Story,Normal,No,No,drama,No,Yes,No,Zulfi Sayed,Akbar Khan,Naushad,135,100000000,31065000
1697,Mr. Hot Mr. Kool,Normal,No,No,comedy,No,No,Yes,Zulfi Sayed,Partho Ghosh,Rishi - Ranjit,30,27500000,1300000

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1698 entries, 0 to 1697
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Movie_Name          1698 non-null   object
 1   Release_Period      1698 non-null   object
 2   Whether_Remake      1698 non-null   object
 3   Whether_Franchise   1698 non-null   object
 4   Genre               1698 non-null   object
 5   New_Actor           1698 non-null   object
 6   New_Director        1698 non-null   object
 7   New_Music_Director  1698 non-null   object
 8   Lead_Star           1698 non-null   object
 9   Director            1698 non-null   object
 10  Music_Director      1698 non-null   object
 11  Number_of_Screens   1698 non-null   int64
 12  Revenue(INR)        1698 non-null   int64
 13  Budget(INR)         1698 non-null   int64
dtypes: int64(3), object(11)
memory usage: 185.8+ KB

In [57]:
df.describe()

       Number_of_Screens  Revenue(INR)   Budget(INR)
count        1698.000000  1.698000e+03  1.698000e+03
mean          553.831567  1.501674e+08  2.377287e+08
std           782.951839  2.434838e+08  6.134398e+08
min             1.000000  3.250000e+05  7.250000e+03
25%            30.000000  1.500000e+07  1.150000e+06
50%           200.000000  5.500000e+07  1.240000e+07
75%           800.000000  1.900000e+08  1.778325e+08
max          4600.000000  2.100000e+09  8.016120e+09

In [58]:
df.isnull().sum()

Movie_Name            0
Release_Period        0
Whether_Remake        0
Whether_Franchise     0
Genre                 0
New_Actor             0
New_Director          0
New_Music_Director    0
Lead_Star             0
Director              0
Music_Director        0
Number_of_Screens     0
Revenue(INR)          0
Budget(INR)           0
dtype: int64

In [59]:
df.duplicated().sum()

np.int64(2)

In [60]:
df.dropna(inplace = True)

In [61]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [62]:
le= LabelEncoder()

In [63]:
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder

binary_map = {
    "Yes": 1,
    "No": 0
}

df["Whether_Remake"] = df["Whether_Remake"].map(binary_map)
df["Whether_Franchise"] = df["Whether_Franchise"].map(binary_map)
df["New_Actor"] = df["New_Actor"].map(binary_map)
df["New_Director"] = df["New_Director"].map(binary_map)
df["New_Music_Director"] = df["New_Music_Director"].map(binary_map)


df["Release_Period"] = le.fit_transform(df["Release_Period"])


df["Lead_Star"] = le.fit_transform(df["Lead_Star"])

df["Director"] = le.fit_transform(df["Director"])

df["Music_Director"] = le.fit_transform(df["Music_Director"])

In [64]:
df

,Movie_Name,Release_Period,Whether_Remake,Whether_Franchise,Genre,New_Actor,New_Director,New_Music_Director,Lead_Star,Director,Music_Director,Number_of_Screens,Revenue(INR),Budget(INR)
0,Golden Boys,1,0,0,suspense,1,0,0,260,710,103,5,5000000,85000
1,Kaccha Limboo,0,0,0,drama,1,0,1,282,754,49,75,15000000,825000
2,Not A Love Story,0,0,0,thriller,0,0,0,328,689,461,525,75000000,56700000
3,Qaidi Band,0,0,0,drama,1,0,0,0,303,54,800,210000000,4500000
4,Chaatwali,0,0,0,adult,1,1,1,1,4,108,1,1000000,1075000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1693,Fight Club,0,0,0,action,0,1,0,761,1000,386,375,82500000,88862500
1694,Strings Of Paasion,1,0,0,drama,0,1,1,762,777,157,10,8000000,70000
1695,Dunno Y Na Jaane Kyun,1,0,0,drama,0,0,0,762,795,336,20,12500000,850000
1696,Taj Mahal - An Eternal Love Story,1,0,0,drama,0,1,0,763,57,326,135,100000000,31065000
1697,Mr. Hot Mr. Kool,1,0,0,comedy,0,0,1,763,575,431,30,27500000,1300000

In [65]:
X = df.drop(columns=["Movie_Name", "Genre"])
y = df["Genre"]

In [66]:
X_train, X_test, y_train, y_test= train_test_split(x, y, random_state=42, test_size=0.2)

In [67]:
from sklearn.neighbors import KNeighborsClassifier

In [68]:
knc=KNeighborsClassifier(n_neighbors=5)

In [69]:
knc.fit(X_train, y_train)

KNeighborsClassifier()

In [70]:
pred = knc.predict(X_test)

In [71]:
from sklearn.metrics import classification_report
print(classification_report(y_test , pred))

              precision    recall  f1-score   support

      action       0.12      0.10      0.11        31
       adult       0.62      0.59      0.61        17
   animation       0.00      0.00      0.00         1
      comedy       0.20      0.35      0.25        52
       drama       0.44      0.61      0.51       126
     fantasy       0.00      0.00      0.00         5
      horror       0.33      0.10      0.15        10
  love_story       0.00      0.00      0.00        28
      masala       0.00      0.00      0.00         5
mythological       0.00      0.00      0.00         4
    rom__com       0.00      0.00      0.00        13
    suspense       0.00      0.00      0.00         8
    thriller       0.27      0.07      0.12        40

    accuracy                           0.33       340
   macro avg       0.15      0.14      0.13       340
weighted avg       0.28      0.33      0.29       340

/Users/Aashi_Dixit/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/Aashi_Dixit/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/Aashi_Dixit/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [72]:
import pickle
with open("KNN_Classifier_pickle.pkl", "wb") as file:
    pickle .dump(knc, file)